# DenseArray specializations for jagged shapes.

package(
    default_applicable_licenses = [
    ],
    default_visibility = ["//visibility:public"],
)

licenses(["notice"])

cc_library(
    name = "dense_array",
    srcs = ["jagged_shape.cc"],
    hdrs = ["jagged_shape.h"],
    deps = [
        "//arolla/dense_array",
        "//arolla/jagged_shape",
        "//arolla/jagged_shape/util",
        "//arolla/util",
    ],
)
