# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# IPython based REPL for Arolla.

load("@pip_deps//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_binary", "py_library")

licenses(["notice"])

exports_files(
    ["start_ipython.py"],
    visibility = ["//visibility:public"],
)

py_library(
    name = "start_ipython",
    srcs = ["start_ipython.py"],
    visibility = ["//visibility:public"],
    deps = [
        requirement("ipython"),
        "//py/arolla:arolla_full",  # build_cleaner: keep
        requirement("numpy"),  # build_cleaner: keep
    ],
)

py_binary(
    name = "ipython",
    srcs = [":start_ipython"],
    main = ":start_ipython.py",
    deps = [":start_ipython"],
)
