# proto-file: arolla/proto/io.proto
# proto-message: ModelInputOutputInfo
inputs {
  name: "foo/plus1"
}
inputs {
  name: "foo/bit0"
}
side_outputs {
  name: "foo/plus1_bit0"
}
side_outputs {
  name: "foo/bit0_plus1"
}
side_outputs {
  name: "double"
}
