# proto-file: arolla/proto/io.proto
# proto-message: ModelInputOutputInfo
inputs {
  name: "foo/self"
}
inputs {
  name: "foo/bit0"
}
inputs {
  name: "bar/self"
}
side_outputs {
  name: "foo/self_bit0"
}
side_outputs {
  name: "foo/bit0_self"
}
side_outputs {
  name: "bar/self"
}
side_outputs {
  name: "double"
}
