# proto-file: arolla/proto/io.proto
# proto-message: ModelInputOutputInfo
inputs {
  name: "self"
}
inputs {
  name: "bit0"
}
side_outputs {
  name: "self_bit0"
}
side_outputs {
  name: "bit0_self"
}
