
package_group(
    name = "internal",
    packages = [
        # make sure we can define codegen models in the directories without explicit dependency.
        "-//python/arolla/expr/codegen/testing/...",
        "//python/arolla/...",
        "//arolla/...",
    ],
)

package(
    default_applicable_licenses = [
    ],
    default_visibility = ["//visibility:public"],
)

licenses(["notice"])

exports_files(["LICENSE"])
